version: 1.0.0.1.{build}
image: Visual Studio 2017


environment:
  matrix:
    - PlatformToolset: v140_xp

platform:
    - x64
    - x86

configuration:
    - Release
    - Debug


install:
    - if "%platform%"=="x64" set archi=amd64
    - if "%platform%"=="x64" set platform_input=x64

    - if "%platform%"=="x86" set archi=x86
    - if "%platform%"=="x86" set platform_input=x86

    - if "%PlatformToolset%"=="v140_xp" call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %archi%
    - if "%PlatformToolset%"=="v141_xp" call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %archi%


build_script:
    - cd "%APPVEYOR_BUILD_FOLDER%"
    - msbuild NppFavorites.sln /m /p:configuration="%configuration%" /p:platform="%platform_input%" /p:PlatformToolset="%PlatformToolset%"

after_build:
    - cd "%APPVEYOR_BUILD_FOLDER%"
    - ps: >-

        if ($env:CONFIGURATION -eq "Release") {
          Push-AppveyorArtifact "bin$($env:PLATFORM_INPUT)\NppFavorites.dll" -FileName NppFavorites.dll          

          if ($env:APPVEYOR_REPO_TAG -eq "true") {
            $ZipFileName = "NppFavorites_$($env:APPVEYOR_REPO_TAG_NAME)_$($env:PLATFORM_INPUT).zip"
            7z a $ZipFileName ".\bin$($env:PLATFORM_INPUT)\NppFavorites.dll"
          }
        }

artifacts:
  - path: NppFavorites_*.zip
    name: releases

deploy:
    provider: GitHub
    auth_token:
        secure: N0ceVFEIoC72u4Igr+eKn4tMrmwJIjOH0FUXZ6XNbdZ4uLLCWIHRf5lil0ApIdJm
    artifact: releases
    draft: false
    prerelease: false
    force_update: true
    on:
        appveyor_repo_tag: true
        PlatformToolset: v140_xp
        configuration: Release
